// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgShare_controller.proto

package com.jessice.mscontroller;

/**
 * <pre>
 *给定请求url而对应的矩阵，如果文件不存在，返回空
 * </pre>
 *
 * Protobuf type {@code mscontroller.Matrix}
 */
public  final class Matrix extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mscontroller.Matrix)
    MatrixOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Matrix.newBuilder() to construct.
  private Matrix(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Matrix() {
    mx_ = 0;
    my_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Matrix(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            mx_ = input.readInt32();
            break;
          }
          case 16: {

            my_ = input.readInt32();
            break;
          }
          case 26: {
            com.jessice.mscontroller.UUrl.Builder subBuilder = null;
            if (urlLocation_ != null) {
              subBuilder = urlLocation_.toBuilder();
            }
            urlLocation_ = input.readMessage(com.jessice.mscontroller.UUrl.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(urlLocation_);
              urlLocation_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_Matrix_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_Matrix_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jessice.mscontroller.Matrix.class, com.jessice.mscontroller.Matrix.Builder.class);
  }

  public static final int MX_FIELD_NUMBER = 1;
  private int mx_;
  /**
   * <code>int32 Mx = 1;</code>
   */
  public int getMx() {
    return mx_;
  }

  public static final int MY_FIELD_NUMBER = 2;
  private int my_;
  /**
   * <code>int32 My = 2;</code>
   */
  public int getMy() {
    return my_;
  }

  public static final int URLLOCATION_FIELD_NUMBER = 3;
  private com.jessice.mscontroller.UUrl urlLocation_;
  /**
   * <code>.mscontroller.UUrl urlLocation = 3;</code>
   */
  public boolean hasUrlLocation() {
    return urlLocation_ != null;
  }
  /**
   * <code>.mscontroller.UUrl urlLocation = 3;</code>
   */
  public com.jessice.mscontroller.UUrl getUrlLocation() {
    return urlLocation_ == null ? com.jessice.mscontroller.UUrl.getDefaultInstance() : urlLocation_;
  }
  /**
   * <code>.mscontroller.UUrl urlLocation = 3;</code>
   */
  public com.jessice.mscontroller.UUrlOrBuilder getUrlLocationOrBuilder() {
    return getUrlLocation();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mx_ != 0) {
      output.writeInt32(1, mx_);
    }
    if (my_ != 0) {
      output.writeInt32(2, my_);
    }
    if (urlLocation_ != null) {
      output.writeMessage(3, getUrlLocation());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mx_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, mx_);
    }
    if (my_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, my_);
    }
    if (urlLocation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getUrlLocation());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jessice.mscontroller.Matrix)) {
      return super.equals(obj);
    }
    com.jessice.mscontroller.Matrix other = (com.jessice.mscontroller.Matrix) obj;

    boolean result = true;
    result = result && (getMx()
        == other.getMx());
    result = result && (getMy()
        == other.getMy());
    result = result && (hasUrlLocation() == other.hasUrlLocation());
    if (hasUrlLocation()) {
      result = result && getUrlLocation()
          .equals(other.getUrlLocation());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MX_FIELD_NUMBER;
    hash = (53 * hash) + getMx();
    hash = (37 * hash) + MY_FIELD_NUMBER;
    hash = (53 * hash) + getMy();
    if (hasUrlLocation()) {
      hash = (37 * hash) + URLLOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getUrlLocation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jessice.mscontroller.Matrix parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jessice.mscontroller.Matrix parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.Matrix parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.Matrix parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jessice.mscontroller.Matrix prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *给定请求url而对应的矩阵，如果文件不存在，返回空
   * </pre>
   *
   * Protobuf type {@code mscontroller.Matrix}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mscontroller.Matrix)
      com.jessice.mscontroller.MatrixOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_Matrix_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_Matrix_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jessice.mscontroller.Matrix.class, com.jessice.mscontroller.Matrix.Builder.class);
    }

    // Construct using com.jessice.mscontroller.Matrix.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      mx_ = 0;

      my_ = 0;

      if (urlLocationBuilder_ == null) {
        urlLocation_ = null;
      } else {
        urlLocation_ = null;
        urlLocationBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_Matrix_descriptor;
    }

    public com.jessice.mscontroller.Matrix getDefaultInstanceForType() {
      return com.jessice.mscontroller.Matrix.getDefaultInstance();
    }

    public com.jessice.mscontroller.Matrix build() {
      com.jessice.mscontroller.Matrix result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jessice.mscontroller.Matrix buildPartial() {
      com.jessice.mscontroller.Matrix result = new com.jessice.mscontroller.Matrix(this);
      result.mx_ = mx_;
      result.my_ = my_;
      if (urlLocationBuilder_ == null) {
        result.urlLocation_ = urlLocation_;
      } else {
        result.urlLocation_ = urlLocationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jessice.mscontroller.Matrix) {
        return mergeFrom((com.jessice.mscontroller.Matrix)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jessice.mscontroller.Matrix other) {
      if (other == com.jessice.mscontroller.Matrix.getDefaultInstance()) return this;
      if (other.getMx() != 0) {
        setMx(other.getMx());
      }
      if (other.getMy() != 0) {
        setMy(other.getMy());
      }
      if (other.hasUrlLocation()) {
        mergeUrlLocation(other.getUrlLocation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jessice.mscontroller.Matrix parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jessice.mscontroller.Matrix) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int mx_ ;
    /**
     * <code>int32 Mx = 1;</code>
     */
    public int getMx() {
      return mx_;
    }
    /**
     * <code>int32 Mx = 1;</code>
     */
    public Builder setMx(int value) {
      
      mx_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 Mx = 1;</code>
     */
    public Builder clearMx() {
      
      mx_ = 0;
      onChanged();
      return this;
    }

    private int my_ ;
    /**
     * <code>int32 My = 2;</code>
     */
    public int getMy() {
      return my_;
    }
    /**
     * <code>int32 My = 2;</code>
     */
    public Builder setMy(int value) {
      
      my_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 My = 2;</code>
     */
    public Builder clearMy() {
      
      my_ = 0;
      onChanged();
      return this;
    }

    private com.jessice.mscontroller.UUrl urlLocation_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder> urlLocationBuilder_;
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    public boolean hasUrlLocation() {
      return urlLocationBuilder_ != null || urlLocation_ != null;
    }
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    public com.jessice.mscontroller.UUrl getUrlLocation() {
      if (urlLocationBuilder_ == null) {
        return urlLocation_ == null ? com.jessice.mscontroller.UUrl.getDefaultInstance() : urlLocation_;
      } else {
        return urlLocationBuilder_.getMessage();
      }
    }
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    public Builder setUrlLocation(com.jessice.mscontroller.UUrl value) {
      if (urlLocationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        urlLocation_ = value;
        onChanged();
      } else {
        urlLocationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    public Builder setUrlLocation(
        com.jessice.mscontroller.UUrl.Builder builderForValue) {
      if (urlLocationBuilder_ == null) {
        urlLocation_ = builderForValue.build();
        onChanged();
      } else {
        urlLocationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    public Builder mergeUrlLocation(com.jessice.mscontroller.UUrl value) {
      if (urlLocationBuilder_ == null) {
        if (urlLocation_ != null) {
          urlLocation_ =
            com.jessice.mscontroller.UUrl.newBuilder(urlLocation_).mergeFrom(value).buildPartial();
        } else {
          urlLocation_ = value;
        }
        onChanged();
      } else {
        urlLocationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    public Builder clearUrlLocation() {
      if (urlLocationBuilder_ == null) {
        urlLocation_ = null;
        onChanged();
      } else {
        urlLocation_ = null;
        urlLocationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    public com.jessice.mscontroller.UUrl.Builder getUrlLocationBuilder() {
      
      onChanged();
      return getUrlLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    public com.jessice.mscontroller.UUrlOrBuilder getUrlLocationOrBuilder() {
      if (urlLocationBuilder_ != null) {
        return urlLocationBuilder_.getMessageOrBuilder();
      } else {
        return urlLocation_ == null ?
            com.jessice.mscontroller.UUrl.getDefaultInstance() : urlLocation_;
      }
    }
    /**
     * <code>.mscontroller.UUrl urlLocation = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder> 
        getUrlLocationFieldBuilder() {
      if (urlLocationBuilder_ == null) {
        urlLocationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder>(
                getUrlLocation(),
                getParentForChildren(),
                isClean());
        urlLocation_ = null;
      }
      return urlLocationBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mscontroller.Matrix)
  }

  // @@protoc_insertion_point(class_scope:mscontroller.Matrix)
  private static final com.jessice.mscontroller.Matrix DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jessice.mscontroller.Matrix();
  }

  public static com.jessice.mscontroller.Matrix getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Matrix>
      PARSER = new com.google.protobuf.AbstractParser<Matrix>() {
    public Matrix parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Matrix(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Matrix> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Matrix> getParserForType() {
    return PARSER;
  }

  public com.jessice.mscontroller.Matrix getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

