// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgShare_controller.proto

package com.jessice.mscontroller;

/**
 * <pre>
 *矩阵表存在的数据库，相当于文件拓扑中对应文件应该返回的矩阵，对应表
 * </pre>
 *
 * Protobuf type {@code mscontroller.MatrixDatabase}
 */
public  final class MatrixDatabase extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mscontroller.MatrixDatabase)
    MatrixDatabaseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MatrixDatabase.newBuilder() to construct.
  private MatrixDatabase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MatrixDatabase() {
    matrix_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MatrixDatabase(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              matrix_ = new java.util.ArrayList<com.jessice.mscontroller.Matrix>();
              mutable_bitField0_ |= 0x00000001;
            }
            matrix_.add(
                input.readMessage(com.jessice.mscontroller.Matrix.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        matrix_ = java.util.Collections.unmodifiableList(matrix_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_MatrixDatabase_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_MatrixDatabase_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jessice.mscontroller.MatrixDatabase.class, com.jessice.mscontroller.MatrixDatabase.Builder.class);
  }

  public static final int MATRIX_FIELD_NUMBER = 1;
  private java.util.List<com.jessice.mscontroller.Matrix> matrix_;
  /**
   * <code>repeated .mscontroller.Matrix matrix = 1;</code>
   */
  public java.util.List<com.jessice.mscontroller.Matrix> getMatrixList() {
    return matrix_;
  }
  /**
   * <code>repeated .mscontroller.Matrix matrix = 1;</code>
   */
  public java.util.List<? extends com.jessice.mscontroller.MatrixOrBuilder> 
      getMatrixOrBuilderList() {
    return matrix_;
  }
  /**
   * <code>repeated .mscontroller.Matrix matrix = 1;</code>
   */
  public int getMatrixCount() {
    return matrix_.size();
  }
  /**
   * <code>repeated .mscontroller.Matrix matrix = 1;</code>
   */
  public com.jessice.mscontroller.Matrix getMatrix(int index) {
    return matrix_.get(index);
  }
  /**
   * <code>repeated .mscontroller.Matrix matrix = 1;</code>
   */
  public com.jessice.mscontroller.MatrixOrBuilder getMatrixOrBuilder(
      int index) {
    return matrix_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < matrix_.size(); i++) {
      output.writeMessage(1, matrix_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < matrix_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, matrix_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jessice.mscontroller.MatrixDatabase)) {
      return super.equals(obj);
    }
    com.jessice.mscontroller.MatrixDatabase other = (com.jessice.mscontroller.MatrixDatabase) obj;

    boolean result = true;
    result = result && getMatrixList()
        .equals(other.getMatrixList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMatrixCount() > 0) {
      hash = (37 * hash) + MATRIX_FIELD_NUMBER;
      hash = (53 * hash) + getMatrixList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jessice.mscontroller.MatrixDatabase parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.MatrixDatabase parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jessice.mscontroller.MatrixDatabase prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *矩阵表存在的数据库，相当于文件拓扑中对应文件应该返回的矩阵，对应表
   * </pre>
   *
   * Protobuf type {@code mscontroller.MatrixDatabase}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mscontroller.MatrixDatabase)
      com.jessice.mscontroller.MatrixDatabaseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_MatrixDatabase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_MatrixDatabase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jessice.mscontroller.MatrixDatabase.class, com.jessice.mscontroller.MatrixDatabase.Builder.class);
    }

    // Construct using com.jessice.mscontroller.MatrixDatabase.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMatrixFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (matrixBuilder_ == null) {
        matrix_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        matrixBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_MatrixDatabase_descriptor;
    }

    public com.jessice.mscontroller.MatrixDatabase getDefaultInstanceForType() {
      return com.jessice.mscontroller.MatrixDatabase.getDefaultInstance();
    }

    public com.jessice.mscontroller.MatrixDatabase build() {
      com.jessice.mscontroller.MatrixDatabase result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jessice.mscontroller.MatrixDatabase buildPartial() {
      com.jessice.mscontroller.MatrixDatabase result = new com.jessice.mscontroller.MatrixDatabase(this);
      int from_bitField0_ = bitField0_;
      if (matrixBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          matrix_ = java.util.Collections.unmodifiableList(matrix_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.matrix_ = matrix_;
      } else {
        result.matrix_ = matrixBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jessice.mscontroller.MatrixDatabase) {
        return mergeFrom((com.jessice.mscontroller.MatrixDatabase)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jessice.mscontroller.MatrixDatabase other) {
      if (other == com.jessice.mscontroller.MatrixDatabase.getDefaultInstance()) return this;
      if (matrixBuilder_ == null) {
        if (!other.matrix_.isEmpty()) {
          if (matrix_.isEmpty()) {
            matrix_ = other.matrix_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatrixIsMutable();
            matrix_.addAll(other.matrix_);
          }
          onChanged();
        }
      } else {
        if (!other.matrix_.isEmpty()) {
          if (matrixBuilder_.isEmpty()) {
            matrixBuilder_.dispose();
            matrixBuilder_ = null;
            matrix_ = other.matrix_;
            bitField0_ = (bitField0_ & ~0x00000001);
            matrixBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMatrixFieldBuilder() : null;
          } else {
            matrixBuilder_.addAllMessages(other.matrix_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jessice.mscontroller.MatrixDatabase parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jessice.mscontroller.MatrixDatabase) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.jessice.mscontroller.Matrix> matrix_ =
      java.util.Collections.emptyList();
    private void ensureMatrixIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        matrix_ = new java.util.ArrayList<com.jessice.mscontroller.Matrix>(matrix_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jessice.mscontroller.Matrix, com.jessice.mscontroller.Matrix.Builder, com.jessice.mscontroller.MatrixOrBuilder> matrixBuilder_;

    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public java.util.List<com.jessice.mscontroller.Matrix> getMatrixList() {
      if (matrixBuilder_ == null) {
        return java.util.Collections.unmodifiableList(matrix_);
      } else {
        return matrixBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public int getMatrixCount() {
      if (matrixBuilder_ == null) {
        return matrix_.size();
      } else {
        return matrixBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public com.jessice.mscontroller.Matrix getMatrix(int index) {
      if (matrixBuilder_ == null) {
        return matrix_.get(index);
      } else {
        return matrixBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder setMatrix(
        int index, com.jessice.mscontroller.Matrix value) {
      if (matrixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrixIsMutable();
        matrix_.set(index, value);
        onChanged();
      } else {
        matrixBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder setMatrix(
        int index, com.jessice.mscontroller.Matrix.Builder builderForValue) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        matrix_.set(index, builderForValue.build());
        onChanged();
      } else {
        matrixBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder addMatrix(com.jessice.mscontroller.Matrix value) {
      if (matrixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrixIsMutable();
        matrix_.add(value);
        onChanged();
      } else {
        matrixBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder addMatrix(
        int index, com.jessice.mscontroller.Matrix value) {
      if (matrixBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMatrixIsMutable();
        matrix_.add(index, value);
        onChanged();
      } else {
        matrixBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder addMatrix(
        com.jessice.mscontroller.Matrix.Builder builderForValue) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        matrix_.add(builderForValue.build());
        onChanged();
      } else {
        matrixBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder addMatrix(
        int index, com.jessice.mscontroller.Matrix.Builder builderForValue) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        matrix_.add(index, builderForValue.build());
        onChanged();
      } else {
        matrixBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder addAllMatrix(
        java.lang.Iterable<? extends com.jessice.mscontroller.Matrix> values) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, matrix_);
        onChanged();
      } else {
        matrixBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder clearMatrix() {
      if (matrixBuilder_ == null) {
        matrix_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        matrixBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public Builder removeMatrix(int index) {
      if (matrixBuilder_ == null) {
        ensureMatrixIsMutable();
        matrix_.remove(index);
        onChanged();
      } else {
        matrixBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public com.jessice.mscontroller.Matrix.Builder getMatrixBuilder(
        int index) {
      return getMatrixFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public com.jessice.mscontroller.MatrixOrBuilder getMatrixOrBuilder(
        int index) {
      if (matrixBuilder_ == null) {
        return matrix_.get(index);  } else {
        return matrixBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public java.util.List<? extends com.jessice.mscontroller.MatrixOrBuilder> 
         getMatrixOrBuilderList() {
      if (matrixBuilder_ != null) {
        return matrixBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(matrix_);
      }
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public com.jessice.mscontroller.Matrix.Builder addMatrixBuilder() {
      return getMatrixFieldBuilder().addBuilder(
          com.jessice.mscontroller.Matrix.getDefaultInstance());
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public com.jessice.mscontroller.Matrix.Builder addMatrixBuilder(
        int index) {
      return getMatrixFieldBuilder().addBuilder(
          index, com.jessice.mscontroller.Matrix.getDefaultInstance());
    }
    /**
     * <code>repeated .mscontroller.Matrix matrix = 1;</code>
     */
    public java.util.List<com.jessice.mscontroller.Matrix.Builder> 
         getMatrixBuilderList() {
      return getMatrixFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.jessice.mscontroller.Matrix, com.jessice.mscontroller.Matrix.Builder, com.jessice.mscontroller.MatrixOrBuilder> 
        getMatrixFieldBuilder() {
      if (matrixBuilder_ == null) {
        matrixBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.jessice.mscontroller.Matrix, com.jessice.mscontroller.Matrix.Builder, com.jessice.mscontroller.MatrixOrBuilder>(
                matrix_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        matrix_ = null;
      }
      return matrixBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mscontroller.MatrixDatabase)
  }

  // @@protoc_insertion_point(class_scope:mscontroller.MatrixDatabase)
  private static final com.jessice.mscontroller.MatrixDatabase DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jessice.mscontroller.MatrixDatabase();
  }

  public static com.jessice.mscontroller.MatrixDatabase getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatrixDatabase>
      PARSER = new com.google.protobuf.AbstractParser<MatrixDatabase>() {
    public MatrixDatabase parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MatrixDatabase(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MatrixDatabase> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatrixDatabase> getParserForType() {
    return PARSER;
  }

  public com.jessice.mscontroller.MatrixDatabase getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

