// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgShare_controller.proto

package com.jessice.mscontroller;

/**
 * <pre>
 *表示矩阵的两个点的UUrl
 * </pre>
 *
 * Protobuf type {@code mscontroller.RectangleUrl}
 */
public  final class RectangleUrl extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mscontroller.RectangleUrl)
    RectangleUrlOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RectangleUrl.newBuilder() to construct.
  private RectangleUrl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RectangleUrl() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RectangleUrl(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.jessice.mscontroller.UUrl.Builder subBuilder = null;
            if (lo_ != null) {
              subBuilder = lo_.toBuilder();
            }
            lo_ = input.readMessage(com.jessice.mscontroller.UUrl.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lo_);
              lo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.jessice.mscontroller.UUrl.Builder subBuilder = null;
            if (hi_ != null) {
              subBuilder = hi_.toBuilder();
            }
            hi_ = input.readMessage(com.jessice.mscontroller.UUrl.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(hi_);
              hi_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_RectangleUrl_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_RectangleUrl_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jessice.mscontroller.RectangleUrl.class, com.jessice.mscontroller.RectangleUrl.Builder.class);
  }

  public static final int LO_FIELD_NUMBER = 1;
  private com.jessice.mscontroller.UUrl lo_;
  /**
   * <code>.mscontroller.UUrl lo = 1;</code>
   */
  public boolean hasLo() {
    return lo_ != null;
  }
  /**
   * <code>.mscontroller.UUrl lo = 1;</code>
   */
  public com.jessice.mscontroller.UUrl getLo() {
    return lo_ == null ? com.jessice.mscontroller.UUrl.getDefaultInstance() : lo_;
  }
  /**
   * <code>.mscontroller.UUrl lo = 1;</code>
   */
  public com.jessice.mscontroller.UUrlOrBuilder getLoOrBuilder() {
    return getLo();
  }

  public static final int HI_FIELD_NUMBER = 2;
  private com.jessice.mscontroller.UUrl hi_;
  /**
   * <code>.mscontroller.UUrl hi = 2;</code>
   */
  public boolean hasHi() {
    return hi_ != null;
  }
  /**
   * <code>.mscontroller.UUrl hi = 2;</code>
   */
  public com.jessice.mscontroller.UUrl getHi() {
    return hi_ == null ? com.jessice.mscontroller.UUrl.getDefaultInstance() : hi_;
  }
  /**
   * <code>.mscontroller.UUrl hi = 2;</code>
   */
  public com.jessice.mscontroller.UUrlOrBuilder getHiOrBuilder() {
    return getHi();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lo_ != null) {
      output.writeMessage(1, getLo());
    }
    if (hi_ != null) {
      output.writeMessage(2, getHi());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLo());
    }
    if (hi_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHi());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jessice.mscontroller.RectangleUrl)) {
      return super.equals(obj);
    }
    com.jessice.mscontroller.RectangleUrl other = (com.jessice.mscontroller.RectangleUrl) obj;

    boolean result = true;
    result = result && (hasLo() == other.hasLo());
    if (hasLo()) {
      result = result && getLo()
          .equals(other.getLo());
    }
    result = result && (hasHi() == other.hasHi());
    if (hasHi()) {
      result = result && getHi()
          .equals(other.getHi());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLo()) {
      hash = (37 * hash) + LO_FIELD_NUMBER;
      hash = (53 * hash) + getLo().hashCode();
    }
    if (hasHi()) {
      hash = (37 * hash) + HI_FIELD_NUMBER;
      hash = (53 * hash) + getHi().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jessice.mscontroller.RectangleUrl parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jessice.mscontroller.RectangleUrl parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.RectangleUrl parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.RectangleUrl parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jessice.mscontroller.RectangleUrl prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *表示矩阵的两个点的UUrl
   * </pre>
   *
   * Protobuf type {@code mscontroller.RectangleUrl}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mscontroller.RectangleUrl)
      com.jessice.mscontroller.RectangleUrlOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_RectangleUrl_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_RectangleUrl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jessice.mscontroller.RectangleUrl.class, com.jessice.mscontroller.RectangleUrl.Builder.class);
    }

    // Construct using com.jessice.mscontroller.RectangleUrl.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (loBuilder_ == null) {
        lo_ = null;
      } else {
        lo_ = null;
        loBuilder_ = null;
      }
      if (hiBuilder_ == null) {
        hi_ = null;
      } else {
        hi_ = null;
        hiBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_RectangleUrl_descriptor;
    }

    public com.jessice.mscontroller.RectangleUrl getDefaultInstanceForType() {
      return com.jessice.mscontroller.RectangleUrl.getDefaultInstance();
    }

    public com.jessice.mscontroller.RectangleUrl build() {
      com.jessice.mscontroller.RectangleUrl result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jessice.mscontroller.RectangleUrl buildPartial() {
      com.jessice.mscontroller.RectangleUrl result = new com.jessice.mscontroller.RectangleUrl(this);
      if (loBuilder_ == null) {
        result.lo_ = lo_;
      } else {
        result.lo_ = loBuilder_.build();
      }
      if (hiBuilder_ == null) {
        result.hi_ = hi_;
      } else {
        result.hi_ = hiBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jessice.mscontroller.RectangleUrl) {
        return mergeFrom((com.jessice.mscontroller.RectangleUrl)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jessice.mscontroller.RectangleUrl other) {
      if (other == com.jessice.mscontroller.RectangleUrl.getDefaultInstance()) return this;
      if (other.hasLo()) {
        mergeLo(other.getLo());
      }
      if (other.hasHi()) {
        mergeHi(other.getHi());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jessice.mscontroller.RectangleUrl parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jessice.mscontroller.RectangleUrl) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.jessice.mscontroller.UUrl lo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder> loBuilder_;
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    public boolean hasLo() {
      return loBuilder_ != null || lo_ != null;
    }
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    public com.jessice.mscontroller.UUrl getLo() {
      if (loBuilder_ == null) {
        return lo_ == null ? com.jessice.mscontroller.UUrl.getDefaultInstance() : lo_;
      } else {
        return loBuilder_.getMessage();
      }
    }
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    public Builder setLo(com.jessice.mscontroller.UUrl value) {
      if (loBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lo_ = value;
        onChanged();
      } else {
        loBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    public Builder setLo(
        com.jessice.mscontroller.UUrl.Builder builderForValue) {
      if (loBuilder_ == null) {
        lo_ = builderForValue.build();
        onChanged();
      } else {
        loBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    public Builder mergeLo(com.jessice.mscontroller.UUrl value) {
      if (loBuilder_ == null) {
        if (lo_ != null) {
          lo_ =
            com.jessice.mscontroller.UUrl.newBuilder(lo_).mergeFrom(value).buildPartial();
        } else {
          lo_ = value;
        }
        onChanged();
      } else {
        loBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    public Builder clearLo() {
      if (loBuilder_ == null) {
        lo_ = null;
        onChanged();
      } else {
        lo_ = null;
        loBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    public com.jessice.mscontroller.UUrl.Builder getLoBuilder() {
      
      onChanged();
      return getLoFieldBuilder().getBuilder();
    }
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    public com.jessice.mscontroller.UUrlOrBuilder getLoOrBuilder() {
      if (loBuilder_ != null) {
        return loBuilder_.getMessageOrBuilder();
      } else {
        return lo_ == null ?
            com.jessice.mscontroller.UUrl.getDefaultInstance() : lo_;
      }
    }
    /**
     * <code>.mscontroller.UUrl lo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder> 
        getLoFieldBuilder() {
      if (loBuilder_ == null) {
        loBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder>(
                getLo(),
                getParentForChildren(),
                isClean());
        lo_ = null;
      }
      return loBuilder_;
    }

    private com.jessice.mscontroller.UUrl hi_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder> hiBuilder_;
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    public boolean hasHi() {
      return hiBuilder_ != null || hi_ != null;
    }
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    public com.jessice.mscontroller.UUrl getHi() {
      if (hiBuilder_ == null) {
        return hi_ == null ? com.jessice.mscontroller.UUrl.getDefaultInstance() : hi_;
      } else {
        return hiBuilder_.getMessage();
      }
    }
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    public Builder setHi(com.jessice.mscontroller.UUrl value) {
      if (hiBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hi_ = value;
        onChanged();
      } else {
        hiBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    public Builder setHi(
        com.jessice.mscontroller.UUrl.Builder builderForValue) {
      if (hiBuilder_ == null) {
        hi_ = builderForValue.build();
        onChanged();
      } else {
        hiBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    public Builder mergeHi(com.jessice.mscontroller.UUrl value) {
      if (hiBuilder_ == null) {
        if (hi_ != null) {
          hi_ =
            com.jessice.mscontroller.UUrl.newBuilder(hi_).mergeFrom(value).buildPartial();
        } else {
          hi_ = value;
        }
        onChanged();
      } else {
        hiBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    public Builder clearHi() {
      if (hiBuilder_ == null) {
        hi_ = null;
        onChanged();
      } else {
        hi_ = null;
        hiBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    public com.jessice.mscontroller.UUrl.Builder getHiBuilder() {
      
      onChanged();
      return getHiFieldBuilder().getBuilder();
    }
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    public com.jessice.mscontroller.UUrlOrBuilder getHiOrBuilder() {
      if (hiBuilder_ != null) {
        return hiBuilder_.getMessageOrBuilder();
      } else {
        return hi_ == null ?
            com.jessice.mscontroller.UUrl.getDefaultInstance() : hi_;
      }
    }
    /**
     * <code>.mscontroller.UUrl hi = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder> 
        getHiFieldBuilder() {
      if (hiBuilder_ == null) {
        hiBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.jessice.mscontroller.UUrl, com.jessice.mscontroller.UUrl.Builder, com.jessice.mscontroller.UUrlOrBuilder>(
                getHi(),
                getParentForChildren(),
                isClean());
        hi_ = null;
      }
      return hiBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mscontroller.RectangleUrl)
  }

  // @@protoc_insertion_point(class_scope:mscontroller.RectangleUrl)
  private static final com.jessice.mscontroller.RectangleUrl DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jessice.mscontroller.RectangleUrl();
  }

  public static com.jessice.mscontroller.RectangleUrl getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RectangleUrl>
      PARSER = new com.google.protobuf.AbstractParser<RectangleUrl>() {
    public RectangleUrl parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RectangleUrl(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RectangleUrl> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RectangleUrl> getParserForType() {
    return PARSER;
  }

  public com.jessice.mscontroller.RectangleUrl getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

