// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgShare_controller.proto

package com.jessice.mscontroller;

/**
 * <pre>
 *UrlSummary包含接收到的点的数量，获得已知矩阵的数量，以及覆盖的总距离，和遍历所需要的时间
 * </pre>
 *
 * Protobuf type {@code mscontroller.UrlSummary}
 */
public  final class UrlSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mscontroller.UrlSummary)
    UrlSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UrlSummary.newBuilder() to construct.
  private UrlSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UrlSummary() {
    urlCount_ = 0;
    matrixCount_ = 0;
    distance_ = 0;
    elapsedTime_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UrlSummary(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            urlCount_ = input.readInt32();
            break;
          }
          case 16: {

            matrixCount_ = input.readInt32();
            break;
          }
          case 24: {

            distance_ = input.readInt32();
            break;
          }
          case 32: {

            elapsedTime_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_UrlSummary_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_UrlSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.jessice.mscontroller.UrlSummary.class, com.jessice.mscontroller.UrlSummary.Builder.class);
  }

  public static final int URL_COUNT_FIELD_NUMBER = 1;
  private int urlCount_;
  /**
   * <pre>
   * The number of url received.接收到url的数量
   * </pre>
   *
   * <code>int32 url_count = 1;</code>
   */
  public int getUrlCount() {
    return urlCount_;
  }

  public static final int MATRIX_COUNT_FIELD_NUMBER = 2;
  private int matrixCount_;
  /**
   * <pre>
   *遍历路线时传递的已知矩阵的数量。
   * </pre>
   *
   * <code>int32 matrix_count = 2;</code>
   */
  public int getMatrixCount() {
    return matrixCount_;
  }

  public static final int DISTANCE_FIELD_NUMBER = 3;
  private int distance_;
  /**
   * <pre>
   * The distance covered in metres.距离以米为单位
   * </pre>
   *
   * <code>int32 distance = 3;</code>
   */
  public int getDistance() {
    return distance_;
  }

  public static final int ELAPSED_TIME_FIELD_NUMBER = 4;
  private int elapsedTime_;
  /**
   * <pre>
   * The duration of the traversal in seconds.遍历的持续时间以秒为单位
   * </pre>
   *
   * <code>int32 elapsed_time = 4;</code>
   */
  public int getElapsedTime() {
    return elapsedTime_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (urlCount_ != 0) {
      output.writeInt32(1, urlCount_);
    }
    if (matrixCount_ != 0) {
      output.writeInt32(2, matrixCount_);
    }
    if (distance_ != 0) {
      output.writeInt32(3, distance_);
    }
    if (elapsedTime_ != 0) {
      output.writeInt32(4, elapsedTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (urlCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, urlCount_);
    }
    if (matrixCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, matrixCount_);
    }
    if (distance_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, distance_);
    }
    if (elapsedTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, elapsedTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.jessice.mscontroller.UrlSummary)) {
      return super.equals(obj);
    }
    com.jessice.mscontroller.UrlSummary other = (com.jessice.mscontroller.UrlSummary) obj;

    boolean result = true;
    result = result && (getUrlCount()
        == other.getUrlCount());
    result = result && (getMatrixCount()
        == other.getMatrixCount());
    result = result && (getDistance()
        == other.getDistance());
    result = result && (getElapsedTime()
        == other.getElapsedTime());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + URL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getUrlCount();
    hash = (37 * hash) + MATRIX_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getMatrixCount();
    hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
    hash = (53 * hash) + getDistance();
    hash = (37 * hash) + ELAPSED_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getElapsedTime();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.jessice.mscontroller.UrlSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jessice.mscontroller.UrlSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.UrlSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.jessice.mscontroller.UrlSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.jessice.mscontroller.UrlSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *UrlSummary包含接收到的点的数量，获得已知矩阵的数量，以及覆盖的总距离，和遍历所需要的时间
   * </pre>
   *
   * Protobuf type {@code mscontroller.UrlSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mscontroller.UrlSummary)
      com.jessice.mscontroller.UrlSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_UrlSummary_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_UrlSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jessice.mscontroller.UrlSummary.class, com.jessice.mscontroller.UrlSummary.Builder.class);
    }

    // Construct using com.jessice.mscontroller.UrlSummary.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      urlCount_ = 0;

      matrixCount_ = 0;

      distance_ = 0;

      elapsedTime_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.jessice.mscontroller.MsgShareControllerProto.internal_static_mscontroller_UrlSummary_descriptor;
    }

    public com.jessice.mscontroller.UrlSummary getDefaultInstanceForType() {
      return com.jessice.mscontroller.UrlSummary.getDefaultInstance();
    }

    public com.jessice.mscontroller.UrlSummary build() {
      com.jessice.mscontroller.UrlSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.jessice.mscontroller.UrlSummary buildPartial() {
      com.jessice.mscontroller.UrlSummary result = new com.jessice.mscontroller.UrlSummary(this);
      result.urlCount_ = urlCount_;
      result.matrixCount_ = matrixCount_;
      result.distance_ = distance_;
      result.elapsedTime_ = elapsedTime_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.jessice.mscontroller.UrlSummary) {
        return mergeFrom((com.jessice.mscontroller.UrlSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.jessice.mscontroller.UrlSummary other) {
      if (other == com.jessice.mscontroller.UrlSummary.getDefaultInstance()) return this;
      if (other.getUrlCount() != 0) {
        setUrlCount(other.getUrlCount());
      }
      if (other.getMatrixCount() != 0) {
        setMatrixCount(other.getMatrixCount());
      }
      if (other.getDistance() != 0) {
        setDistance(other.getDistance());
      }
      if (other.getElapsedTime() != 0) {
        setElapsedTime(other.getElapsedTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.jessice.mscontroller.UrlSummary parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.jessice.mscontroller.UrlSummary) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int urlCount_ ;
    /**
     * <pre>
     * The number of url received.接收到url的数量
     * </pre>
     *
     * <code>int32 url_count = 1;</code>
     */
    public int getUrlCount() {
      return urlCount_;
    }
    /**
     * <pre>
     * The number of url received.接收到url的数量
     * </pre>
     *
     * <code>int32 url_count = 1;</code>
     */
    public Builder setUrlCount(int value) {
      
      urlCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The number of url received.接收到url的数量
     * </pre>
     *
     * <code>int32 url_count = 1;</code>
     */
    public Builder clearUrlCount() {
      
      urlCount_ = 0;
      onChanged();
      return this;
    }

    private int matrixCount_ ;
    /**
     * <pre>
     *遍历路线时传递的已知矩阵的数量。
     * </pre>
     *
     * <code>int32 matrix_count = 2;</code>
     */
    public int getMatrixCount() {
      return matrixCount_;
    }
    /**
     * <pre>
     *遍历路线时传递的已知矩阵的数量。
     * </pre>
     *
     * <code>int32 matrix_count = 2;</code>
     */
    public Builder setMatrixCount(int value) {
      
      matrixCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *遍历路线时传递的已知矩阵的数量。
     * </pre>
     *
     * <code>int32 matrix_count = 2;</code>
     */
    public Builder clearMatrixCount() {
      
      matrixCount_ = 0;
      onChanged();
      return this;
    }

    private int distance_ ;
    /**
     * <pre>
     * The distance covered in metres.距离以米为单位
     * </pre>
     *
     * <code>int32 distance = 3;</code>
     */
    public int getDistance() {
      return distance_;
    }
    /**
     * <pre>
     * The distance covered in metres.距离以米为单位
     * </pre>
     *
     * <code>int32 distance = 3;</code>
     */
    public Builder setDistance(int value) {
      
      distance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The distance covered in metres.距离以米为单位
     * </pre>
     *
     * <code>int32 distance = 3;</code>
     */
    public Builder clearDistance() {
      
      distance_ = 0;
      onChanged();
      return this;
    }

    private int elapsedTime_ ;
    /**
     * <pre>
     * The duration of the traversal in seconds.遍历的持续时间以秒为单位
     * </pre>
     *
     * <code>int32 elapsed_time = 4;</code>
     */
    public int getElapsedTime() {
      return elapsedTime_;
    }
    /**
     * <pre>
     * The duration of the traversal in seconds.遍历的持续时间以秒为单位
     * </pre>
     *
     * <code>int32 elapsed_time = 4;</code>
     */
    public Builder setElapsedTime(int value) {
      
      elapsedTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The duration of the traversal in seconds.遍历的持续时间以秒为单位
     * </pre>
     *
     * <code>int32 elapsed_time = 4;</code>
     */
    public Builder clearElapsedTime() {
      
      elapsedTime_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mscontroller.UrlSummary)
  }

  // @@protoc_insertion_point(class_scope:mscontroller.UrlSummary)
  private static final com.jessice.mscontroller.UrlSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.jessice.mscontroller.UrlSummary();
  }

  public static com.jessice.mscontroller.UrlSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UrlSummary>
      PARSER = new com.google.protobuf.AbstractParser<UrlSummary>() {
    public UrlSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UrlSummary(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UrlSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UrlSummary> getParserForType() {
    return PARSER;
  }

  public com.jessice.mscontroller.UrlSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

