// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgShare_controller.proto

package com.jessice.mscontroller;

public interface UUrlOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mscontroller.UUrl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string fileid = 2;</code>
   */
  java.lang.String getFileid();
  /**
   * <code>string fileid = 2;</code>
   */
  com.google.protobuf.ByteString
      getFileidBytes();
}
